using System.Collections;

namespace PrimarieWeb.Models
{

    public class Cetatean
    {
        public int CetateanId { get; set; }
        public string? nume {  get; set; }
        

        //public List<User> ListaUser = new List<User>();
        public ICollection<Eveniment>? Eveniments { get; set; }
        public ICollection<Document>? Documents { get; set; }
        public ICollection<Chat>? Chats { get; set; }
       

    }   
}
//CREATE TABLE "Utilizator" (
//  "id" INT GENERATED BY DEFAULT AS IDENTITY,
//  "nume" varchar(255),
//  "email" varchar(255),
//  "telefon" varchar(255),
//  "parola" varchar(255),
//  "rol" varchar(255),
//  "id_rol" INT GENERATED BY DEFAULT AS IDENTITY,
//  PRIMARY KEY ("id", "id_rol")
//);