namespace PrimarieWeb.Models
{
    public class Chat
    {
        public int ChatId { get; set; }
        public int nrParticipanti { get; set; }
        public DateTime? data { get; set; }

        public int CetateanId { get; set; }
        public Cetatean? Cetatean { get; set; }

    }
}
//CREATE TABLE "Chat" (
//  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//  "nr_participanti" varchar(255),
//  "data" date,
//  "ora" time,
//  "id_cetatean" int,
//  "id_secretar" int
//);