namespace PrimarieWeb.Models
{
    public class Document
    {
        public int DocumentId { get; set; }
        public string? numeDoc {get ; set;}
        public string? descriere { get ; set;}
        public string? urlFisier { get ; set;}
        public int CetateanId { get; set; }
        public Cetatean? Cetatean { get; set; }
    }
}
//CREATE TABLE "Document" (
//  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//  "nume" varchar(255),
//  "descriere" varchar(255),
//  "url_fisier" varchar(255),
//  "id_cetatean" int,
//  "id_secretar" int
//);